use_frameworks!

platform :ios, '9.0'

target 'YFSectionHeaderCollectionView_Example' do
  pod 'YFSectionHeaderCollectionView', :path => '../'

  target 'YFSectionHeaderCollectionView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
