use_frameworks!

platform :ios, '9.0'

target 'YFSectionHeaderCollectionView_Example' do
  pod 'YFSectionHeaderCollectionView', :path => '../'
  
  pod 'LookinServer', '1.0.0', :configurations => ['Debug']

  target 'YFSectionHeaderCollectionView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
